version: '3'
services:
  redis:
    image: redis:latest
    ports:
      - '6379:6379'

  postgres:
    container_name: travel_guide
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=db
